import os
import shutil
import subprocess
Import("env")

# Run web build
print("Building Hono web app...")
root_dir = os.path.join(env.get("PROJECT_DIR"), ".")
subprocess.run(["echo", "hello"], cwd=root_dir, shell=True, check=True)

# Prune LVGL assembly if present to avoid RISC-V linking issues
# This is a workaround for LVGL 9 assembly files causing ABI mismatch in PIO
libdeps_dir = os.path.join(env.get("PROJECT_DIR"), ".pio", "libdeps", env.get("PIOENV"))
lvgl_blend_sw = os.path.join(libdeps_dir, "lvgl", "src", "draw", "sw", "blend")
if os.path.exists(lvgl_blend_sw):
    for folder in ["helium", "neon"]:
        p = os.path.join(lvgl_blend_sw, folder)
        if os.path.exists(p):
            print(f"Pruning LVGL folder: {p}")
            shutil.rmtree(p)

# Override lwIP TCP window size for PlatformIO SCons builds.
# Problem: SCons compiles lwIP using the prebuilt sdkconfig.h from
# framework-arduinoespressif32-libs which has TCP_WND=5760. The ESP-IDF CMake
# build uses our sdkconfig.defaults (TCP_WND=65534), but SCons .o files take
# precedence at link time. We cannot simply prepend the full project sdkconfig.h
# because SPIRAM/PSRAM configs differ from prebuilt libs, causing header errors.
# Solution: Create a minimal sdkconfig.h wrapper that chains to the prebuilt one
# via #include_next and overrides only the lwIP TCP values.
override_dir = os.path.join(
    env.get("PROJECT_DIR"), ".pio", "build", env.get("PIOENV"), "lwip_override"
)
os.makedirs(override_dir, exist_ok=True)
override_header = os.path.join(override_dir, "sdkconfig.h")
with open(override_header, "w") as f:
    f.write("""\
/* Auto-generated by env_loader.py — do not edit */
/* Chain to the prebuilt sdkconfig.h, then override lwIP TCP values */
#ifndef _LWIP_OVERRIDE_SDKCONFIG_H_
#define _LWIP_OVERRIDE_SDKCONFIG_H_

#include_next "sdkconfig.h"


/* Match Hybrid Compile settings that achieved 30fps (TCP_WND=8192).
 * TCP_WND=65534 causes internal SRAM exhaustion (65KB × 4 connections = 260KB
 * out of ~370KB free). TCP_WND=16384+ caused SDIO crashes in Hybrid Compile.
 * TCP_WND=8192 is the proven sweet spot: enough for 30fps (13 Mbps at 5ms RTT)
 * without starving WiFi/SDIO queues. */
#undef CONFIG_LWIP_TCP_WND_DEFAULT
#define CONFIG_LWIP_TCP_WND_DEFAULT 8192

#undef CONFIG_LWIP_TCP_SND_BUF_DEFAULT
#define CONFIG_LWIP_TCP_SND_BUF_DEFAULT 8192

#undef CONFIG_LWIP_TCP_RECVMBOX_SIZE
#define CONFIG_LWIP_TCP_RECVMBOX_SIZE 32

/* Enable SPIRAM allocation for WiFi/lwIP buffers to reduce internal SRAM pressure.
 * This matches the Hybrid Compile config that achieved 30fps. */
#ifndef CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP
#define CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP 1
#endif

#endif /* _LWIP_OVERRIDE_SDKCONFIG_H_ */
""")
env.Prepend(CPPPATH=[override_dir])
print(f"lwIP TCP override: TCP_WND=8192+SPIRAM_WIFI (via {override_dir})")

# Try to load .env file
env_file = os.path.join(env.get("PROJECT_DIR"), ".env")

if os.path.exists(env_file):
    print(f"Loading environment from {env_file}")
    with open(env_file) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            key, value = line.split("=", 1)
            # Remove quotes if present
            value = value.strip('"').strip("'")
            # Inject as build flag
            env.Append(CPPDEFINES=[
                (key, f'\\"{value}\\"')
            ])
else:
    print("Warning: .env file not found!")
